version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
  #app:
   # build:
    #  context: .
     # dockerfile: Dockerfile
    #ports:
     # - "8080:8080"
    #environment:
     # - AWS_ENDPOINT=http://localstack:4566
      #- AWS_REGION=us-east-1
    #depends_on:
     # - localstack
